### ISSUE TITLE
"client connection terminated abruptly" when using the GUI to talk to the service

### ISSUE THREAD

**Issue by hash-bang** [mdoyleaz/Logitech-G560-LED-Controller#1]
I can get the service + GUI programs running successfully but whenever I hit the 'Apply' button the service throws the below:

```
client connection terminated abruptly
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rpyc/utils/server.py", line 179, in _authenticate_and_serve_client
    self._serve_client(sock2, credentials)
  File "/usr/lib/python3/dist-packages/rpyc/utils/server.py", line 201, in _serve_client
    config = config, _lazy = True)
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 157, in __init__
    self._local_root = service(weakref.proxy(self))
TypeError: __init__() takes 1 positional argument but 2 were given
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/rpyc/utils/server.py", line 179, in _authenticate_and_serve_client
    self._serve_client(sock2, credentials)
  File "/usr/lib/python3/dist-packages/rpyc/utils/server.py", line 201, in _serve_client
    config = config, _lazy = True)
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 157, in __init__
    self._local_root = service(weakref.proxy(self))
TypeError: __init__() takes 1 positional argument but 2 were given
```

**Comment by hash-bang** [comment]
I figured this out in the end.

Turns out the Ubuntu python libraries are tragically out of date. Installing them with:

```
sudo apt-get install python3-pip
pip3 install rpyc pyusb
```
... makes everything work fine.

Great work on this module, it works like a charm now.
